name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yaml

  release:
    needs: build
    permissions:
      id-token: write
      contents: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v5
        with:
          node-version: lts/*
          registry-url: https://registry.npmjs.org/

      - run: npm i -g npm@latest
      - run: pnpm i

      - name: Publish to VSCE
        run: pnpx @vscode/vsce publish --no-dependencies -p ${{secrets.VSCE_TOKEN}}

      - name: Publish to OVSX
        run: pnpx ovsx publish --no-dependencies -p ${{secrets.OVSX_TOKEN}}

      - name: Publish to NPM
        working-directory: ./src/sync/ws/
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: Download WS Server Artifact
        uses: actions/download-artifact@v4
        with:
          name: ws-server serverless.zip
      
      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: ws-server, serverless.zip
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
