name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  release:
    permissions:
      id-token: write
      contents: write

    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/build.yaml

      - run: npm i -g npm@latest
      - run: pnpm i

      - name: Publish to VSCE
        run: pnpx @vscode/vsce publish --no-dependencies -p ${{secrets.VSCE_TOKEN}}

      - name: Publish to OVSX
        run: pnpx ovsx publish --no-dependencies -p ${{secrets.OVSX_TOKEN}}

      - name: Publish to NPM
        working-directory: ./src/sync/ws/
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: ./src/sync/ws/ws-server, ./src/sync/ws/serverless.zip
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
